FROM rust:bookworm
RUN useradd --user-group --system --create-home --no-log-init dockerissimo
WORKDIR /code
RUN chown dockerissimo:dockerissimo -R /code
USER dockerissimo
COPY ./src /code/src
COPY ./Cargo.toml /code/Cargo.toml
RUN cargo install cargo-watch
RUN cargo build